"""virements et comptes epargne

Revision ID: 16789562705e
Revises: 679444fcd85e
Create Date: 2026-08-20 01:43:29.805434
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '16789562705e'
down_revision: str | None = '679444fcd85e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compte', sa.Column('type_compte', sa.String(length=16), server_default='courant', nullable=False))
    op.add_column('operation', sa.Column('virement_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_operation_virement_id'), 'operation', ['virement_id'], unique=False)
    op.create_check_constraint(
        'ck_operation_virement_ni_paie_ni_ouverture',
        'operation',
        'not (virement_id is not null and (est_paie or est_ouverture))',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint('ck_operation_virement_ni_paie_ni_ouverture', 'operation', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_virement_id'), table_name='operation')
    op.drop_column('operation', 'virement_id')
    op.drop_column('compte', 'type_compte')
    # ### end Alembic commands ###
