"""annulation dune operation

Revision ID: 679444fcd85e
Revises: b97bfc20836d
Create Date: 2026-08-19 23:46:54.210251
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '679444fcd85e'
down_revision: str | None = 'b97bfc20836d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('annulee', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation', 'annulee')
    # ### end Alembic commands ###
