"""ajustement de solde

Revision ID: 930c766d8746
Revises: aad50a654444
Create Date: 2026-08-20 13:42:13.591650
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '930c766d8746'
down_revision: str | None = 'aad50a654444'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('est_ajustement', sa.Boolean(), server_default='false', nullable=False))
    op.create_check_constraint(op.f('ck_operation_ck_operation_ajustement_seul'), 'operation', 'not (est_ajustement and (est_paie or est_ouverture or virement_id is not null))')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_operation_ck_operation_ajustement_seul'), 'operation', type_='check')
    op.drop_column('operation', 'est_ajustement')
    # ### end Alembic commands ###
