"""reglage paies par cycle

Revision ID: 98f34bb78bee
Revises: ad3889e97a2f
Create Date: 2026-08-19 19:49:47.137171
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '98f34bb78bee'
down_revision: str | None = 'ad3889e97a2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('paies_par_cycle', sa.Integer(), server_default='1', nullable=False))
    op.create_check_constraint('ck_utilisateur_paies_par_cycle', 'utilisateur', 'paies_par_cycle between 1 and 12')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_utilisateur_paies_par_cycle', 'utilisateur', type_='check')
    op.drop_column('utilisateur', 'paies_par_cycle')
    # ### end Alembic commands ###
