"""enveloppes et leur journal

Revision ID: 9af113325c74
Revises: 930c766d8746
Create Date: 2026-08-20 14:53:54.292167
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '9af113325c74'
down_revision: str | None = '930c766d8746'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enveloppe',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('foyer_id', sa.UUID(), nullable=False),
    sa.Column('cree_par_id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('categorie_id', sa.UUID(), nullable=True),
    sa.Column('compte_prefere_id', sa.UUID(), nullable=True),
    sa.Column('cible_centimes', sa.BigInteger(), nullable=True),
    sa.Column('date_cible', sa.Date(), nullable=True),
    sa.Column('archive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cible_centimes is null or cible_centimes > 0', name=op.f('ck_enveloppe_ck_enveloppe_cible_positive')),
    sa.ForeignKeyConstraint(['categorie_id'], ['categorie.id'], name=op.f('fk_enveloppe_categorie_id_categorie'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['compte_prefere_id'], ['compte.id'], name=op.f('fk_enveloppe_compte_prefere_id_compte'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_enveloppe_cree_par_id_utilisateur'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['foyer_id'], ['foyer.id'], name=op.f('fk_enveloppe_foyer_id_foyer'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enveloppe')),
    sa.UniqueConstraint('foyer_id', 'nom', name='uq_enveloppe_nom_par_foyer')
    )
    op.create_table('mouvement_enveloppe',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enveloppe_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('montant_centimes', sa.BigInteger(), nullable=False),
    sa.Column('date_mouvement', sa.Date(), nullable=False),
    sa.Column('libelle', sa.String(length=140), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('montant_centimes > 0', name=op.f('ck_mouvement_enveloppe_ck_mouvement_enveloppe_positif')),
    sa.ForeignKeyConstraint(['enveloppe_id'], ['enveloppe.id'], name=op.f('fk_mouvement_enveloppe_enveloppe_id_enveloppe'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], name=op.f('fk_mouvement_enveloppe_operation_id_operation'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mouvement_enveloppe'))
    )
    op.create_index(op.f('ix_mouvement_enveloppe_enveloppe_id'), 'mouvement_enveloppe', ['enveloppe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mouvement_enveloppe_enveloppe_id'), table_name='mouvement_enveloppe')
    op.drop_table('mouvement_enveloppe')
    op.drop_table('enveloppe')
    # ### end Alembic commands ###
