"""tables d'authentification et de foyer

Revision ID: 9ce50ee2e5aa
Revises: 
Create Date: 2026-08-19 18:45:22.887432
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '9ce50ee2e5aa'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foyer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateur',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('foyer_id', sa.UUID(), nullable=False),
    sa.Column('courriel', sa.String(length=254), nullable=False),
    sa.Column('nom_affichage', sa.String(length=80), nullable=False),
    sa.Column('empreinte_mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('actif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['foyer_id'], ['foyer.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('courriel', name='uq_utilisateur_courriel')
    )
    op.create_table('invitation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('foyer_id', sa.UUID(), nullable=False),
    sa.Column('empreinte_code', sa.String(length=64), nullable=False),
    sa.Column('creee_par_id', sa.UUID(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expire_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('utilisee_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creee_par_id'], ['utilisateur.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['foyer_id'], ['foyer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empreinte_code', name='uq_invitation_empreinte')
    )
    op.create_table('session_web',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('empreinte_jeton', sa.String(length=64), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expire_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empreinte_jeton', name='uq_session_empreinte')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_web')
    op.drop_table('invitation')
    op.drop_table('utilisateur')
    op.drop_table('foyer')
    # ### end Alembic commands ###
