"""produit bancaire du compte

Revision ID: aad50a654444
Revises: 16789562705e
Create Date: 2026-08-20 11:39:23.041907
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'aad50a654444'
down_revision: str | None = '16789562705e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compte', sa.Column('produit', sa.String(length=32), server_default='compte_courant', nullable=False))
    # Les comptes déjà marqués « épargne » reçoivent le produit le plus probable plutôt
    # que « compte courant », qui les ferait paraître ce qu'ils ne sont pas. Le libellé se
    # corrige d'un geste dans les réglages ; un compte courant affiché à la place d'un
    # livret ferait douter du reste.
    op.execute("update compte set produit = 'livret_a' where type_compte = 'epargne'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compte', 'produit')
    # ### end Alembic commands ###
