"""comptes, categories et operations

Revision ID: ad3889e97a2f
Revises: 9ce50ee2e5aa
Create Date: 2026-08-19 19:47:21.830329
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'ad3889e97a2f'
down_revision: str | None = '9ce50ee2e5aa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorie',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('foyer_id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=60), nullable=False),
    sa.Column('nature', sa.String(length=16), nullable=False),
    sa.Column('teinte', sa.String(length=16), nullable=False),
    sa.Column('archivee', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['foyer_id'], ['foyer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('foyer_id', 'nom', name='uq_categorie_nom_par_foyer')
    )
    op.create_table('compte',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('foyer_id', sa.UUID(), nullable=False),
    sa.Column('proprietaire_id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('prive', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('devise', sa.String(length=3), server_default='EUR', nullable=False),
    sa.Column('archive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("devise = 'EUR'", name='ck_compte_devise_eur'),
    sa.ForeignKeyConstraint(['foyer_id'], ['foyer.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proprietaire_id'], ['utilisateur.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('foyer_id', 'nom', name='uq_compte_nom_par_foyer')
    )
    op.create_table('operation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('compte_id', sa.UUID(), nullable=False),
    sa.Column('categorie_id', sa.UUID(), nullable=True),
    sa.Column('cree_par_id', sa.UUID(), nullable=False),
    sa.Column('libelle', sa.String(length=140), nullable=False),
    sa.Column('montant_centimes', sa.BigInteger(), nullable=False),
    sa.Column('date_operation', sa.Date(), nullable=False),
    sa.Column('date_valeur', sa.Date(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('etat', sa.String(length=16), nullable=False),
    sa.Column('est_paie', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint('montant_centimes <> 0', name='ck_operation_montant_non_nul'),
    sa.CheckConstraint('not est_paie or montant_centimes > 0', name='ck_operation_paie_positive'),
    sa.ForeignKeyConstraint(['categorie_id'], ['categorie.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['compte_id'], ['compte.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_operation_compte_date', 'operation', ['compte_id', 'date_operation'], unique=False)
    op.create_index('ix_operation_paie', 'operation', ['compte_id', 'date_operation'], unique=False, postgresql_where='est_paie')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_operation_paie', table_name='operation', postgresql_where='est_paie')
    op.drop_index('ix_operation_compte_date', table_name='operation')
    op.drop_table('operation')
    op.drop_table('compte')
    op.drop_table('categorie')
    # ### end Alembic commands ###
