"""plafonds par categorie

Revision ID: b97bfc20836d
Revises: d5b9e99e651c
Create Date: 2026-08-19 22:42:55.033563
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b97bfc20836d'
down_revision: str | None = 'd5b9e99e651c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plafond',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('categorie_id', sa.UUID(), nullable=False),
    sa.Column('montant_centimes', sa.BigInteger(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('montant_centimes > 0', name=op.f('ck_plafond_ck_plafond_montant_positif')),
    sa.ForeignKeyConstraint(['categorie_id'], ['categorie.id'], name=op.f('fk_plafond_categorie_id_categorie'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], name=op.f('fk_plafond_utilisateur_id_utilisateur'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plafond')),
    sa.UniqueConstraint('utilisateur_id', 'categorie_id', name='uq_plafond_par_categorie_et_personne')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plafond')
    # ### end Alembic commands ###
