"""solde douverture

Revision ID: d35990bd2566
Revises: 98f34bb78bee
Create Date: 2026-08-19 20:16:07.400267
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'd35990bd2566'
down_revision: str | None = '98f34bb78bee'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('est_ouverture', sa.Boolean(), server_default='false', nullable=False))
    op.create_check_constraint('ck_operation_paie_ou_ouverture', 'operation', 'not (est_paie and est_ouverture)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_operation_paie_ou_ouverture', 'operation', type_='check')
    op.drop_column('operation', 'est_ouverture')
    # ### end Alembic commands ###
