"""recurrences

Revision ID: d5b9e99e651c
Revises: d35990bd2566
Create Date: 2026-08-19 21:30:15.497050
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'd5b9e99e651c'
down_revision: str | None = 'd35990bd2566'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurrence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('compte_id', sa.UUID(), nullable=False),
    sa.Column('categorie_id', sa.UUID(), nullable=True),
    sa.Column('cree_par_id', sa.UUID(), nullable=False),
    sa.Column('libelle', sa.String(length=140), nullable=False),
    sa.Column('montant_centimes', sa.BigInteger(), nullable=False),
    sa.Column('ancre', sa.Date(), nullable=False),
    sa.Column('unite', sa.String(length=16), nullable=False),
    sa.Column('intervalle', sa.Integer(), server_default='1', nullable=False),
    sa.Column('fin', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fin is null or fin >= ancre', name='ck_recurrence_fin_apres_ancre'),
    sa.CheckConstraint('intervalle >= 1', name='ck_recurrence_intervalle'),
    sa.CheckConstraint('montant_centimes <> 0', name='ck_recurrence_montant_non_nul'),
    sa.ForeignKeyConstraint(['categorie_id'], ['categorie.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['compte_id'], ['compte.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('operation', sa.Column('recurrence_id', sa.UUID(), nullable=True))
    op.create_index('uq_operation_par_echeance', 'operation', ['recurrence_id', 'date_operation'], unique=True, postgresql_where='recurrence_id is not null')
    op.create_foreign_key(
        'fk_operation_recurrence', 'operation', 'recurrence', ['recurrence_id'], ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_operation_recurrence', 'operation', type_='foreignkey')
    op.drop_index('uq_operation_par_echeance', table_name='operation', postgresql_where='recurrence_id is not null')
    op.drop_column('operation', 'recurrence_id')
    op.drop_table('recurrence')
    # ### end Alembic commands ###
